### ISSUE TITLE
Wrong results when calling *syrk with RowMajor layout; ColumnMajor correct

### ISSUE THREAD

**Issue by SuperFluffy** [blas-lapack-rs/cblas#2]
This is probably an error with openblas/netlib rather than the rust cblas bindings, but since I discovered the error with the rust bindings, I thought I report it here.

I am getting the wrong results when calling `ssyrk` or `dsyrk`. See the simple example below:

```rust
// extern crate openblas_src; // Same results as with netlib
extern crate netlib_src;
fn main() {
    let a_slice = vec![
        1., 1.,
        1., 1.,
        1., 1.,
        1., 1.
    ];
    let mut c_slice = vec![
        0., 0.,
        0., 0.
    ];

    unsafe {
        cblas::ssyrk(
            cblas::Layout::RowMajor, // change to cblas::Layout::ColumnMajor for correct result
            cblas::Part::Upper,
            cblas::Transpose::Ordinary,
            2 as i32,
            4 as i32,
            1.0,
            &a_slice,
            4 as i32,
            0.0,
            &mut c_slice,
            2 as i32,
        );
    }

    println!("{:?}", c_slice);
}
```

This prints `[2.0, 2.0, 0.0, 2.0]`, where I expected `[4.0, 4.0, 0.0, 4.0]`.

When changing the code to `cblas::Layout::ColumMajor`, it gives the correct result!

Any idea what's going on here?

**Comment by IvanUkhov** [comment]
I think it’s due to `LDA`. It should be two, since it’s row major.

**Comment by SuperFluffy** [comment]
Hi, thanks for looking at the code and getting back to me.

Yes, that was it. The documentation on [netlib.org](http://www.netlib.org/lapack/explore-html/d1/d54/group__double__blas__level3_gae0ba56279ae3fa27c75fefbc4cc73ddf.html#gae0ba56279ae3fa27c75fefbc4cc73ddf) is what confused me:

```
LDA is INTEGER

On entry, LDA specifies the first dimension of A as declared in the calling (sub) program.
When TRANS = 'N' or 'n' then LDA must be at least max( 1, n ),
otherwise LDA must be at least max( 1, k ).
```

So `k = 4`, i.e. the number of rows because I pass in `'T'` / `Transpose::Ordinary`. Now if `k=4`, then obviously `max(1,k) = 4`.

But I now realize what `cblas::dsyrk` is doing, i.e. [here](http://www.netlib.org/lapack/explore-html/d0/d53/cblas__dsyrk_8c_acdc3d6fcea19cc5848ae3f5c9f3d796a.html#acdc3d6fcea19cc5848ae3f5c9f3d796a):

It changes `U` to `L` and `T` to `N`, so because we have row major order, we don't want to have dsyrk caculate `A**T * A` but `A * A**T`. But because of row major order, we actually *do* get `A**T * A` after all.


Thanks a lot. I was quite confused about what's going on!
