### ISSUE TITLE
`aimin` is not impl

### ISSUE THREAD

**Issue by bokutotu** [blas-lapack-rs/cblas#6]
Hello!!!

Why is imax implemented but imin is not?

**Comment by IvanUkhov** [comment]
There are no such functions in the reference:

https://github.com/Reference-LAPACK/lapack-release/blob/lapack-3.10.0/CBLAS/include/cblas.h

**Comment by bokutotu** [comment]
@IvanUkhov 
https://github.com/xianyi/OpenBLAS/blob/develop/cblas.h#L98-L101
OpenBlas has such an implementation.

**Comment by IvanUkhov** [comment]
Thank you for the note! It is interesting indeed. The reference for this crate is the one by Netlib. Please let me know if you find out what the difference comes from.
